language: java

before_script:
- echo "Starting dependent containers for testing"
- docker-compose up -d
- echo "Wait for containers to be up and running"
- bash waitForContainerSetup.sh

after_success:
- bash <(curl -s https://codecov.io/bash)

after_script:
- docker-compose down
